# Generated by Django 6.0 on 2026-05-09 09:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminQuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='answers/')),
                ('is_correct', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EssaySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('answer_file', models.FileField(blank=True, null=True, upload_to='essay_submissions/')),
                ('score', models.FloatField(blank=True, null=True)),
                ('is_scored', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('related_to', models.CharField(choices=[('COURSE', 'Course'), ('UNIT', 'Unit')], max_length=10)),
                ('number_of_questions', models.PositiveIntegerField(default=1)),
                ('time_limit', models.PositiveIntegerField(help_text='Time limit in minutes')),
                ('score', models.FloatField(default=0.0)),
                ('passing_percent', models.PositiveIntegerField(default=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('number_of_allowed_trials', models.PositiveIntegerField(default=1)),
                ('type', models.CharField(choices=[('RANDOM', 'Random'), ('MANUAL', 'Manual'), ('BANK', 'Pic From the Bank')], default='MANUAL', max_length=10)),
                ('easy_questions_count', models.PositiveIntegerField(default=0)),
                ('medium_questions_count', models.PositiveIntegerField(default=0)),
                ('hard_questions_count', models.PositiveIntegerField(default=0)),
                ('show_answers_after_finish', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('allow_show_results_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('allow_show_answers_at', models.DateTimeField(blank=True, null=True)),
                ('is_depends', models.BooleanField(default=False)),
                ('show_questions_in_random', models.BooleanField(default=True)),
                ('ponus', models.IntegerField(default=0)),
                ('ponus_option', models.CharField(blank=True, choices=[('student_last_trial_score', 'Student Last Trial Score'), ('fixed_ponus', 'Fixed Ponus')], max_length=30, null=True)),
            ],
            options={
                'ordering': ['order', 'created'],
            },
        ),
        migrations.CreateModel(
            name='ExamModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamModelQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['order', 'created'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/')),
                ('points', models.PositiveIntegerField(default=1)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='EASY', max_length=6)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice Question'), ('ESSAY', 'Essay Question')], default='MCQ', max_length=5)),
                ('comment', models.TextField(blank=True, null=True)),
                ('explanation', models.CharField(blank=True, help_text='Explanation for the question', max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RandomExamBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial', models.PositiveIntegerField(default=0)),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResultTrial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial', models.PositiveIntegerField()),
                ('score', models.FloatField(default=0.0)),
                ('exam_score', models.FloatField(default=0.0)),
                ('student_started_exam_at', models.DateTimeField()),
                ('student_submitted_exam_at', models.DateTimeField(blank=True, null=True)),
                ('submit_type', models.CharField(blank=True, choices=[('student_submit', 'Student Submit'), ('tab_closed', 'Tab Closed'), ('offline', 'Offline'), ('time_out', 'Time Out')], default='student_submit', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_reason', models.CharField(choices=[('INCORRECT', 'Incorrect'), ('UNSOLVED', 'Unsolved'), ('PARTIAL_ESSAY', 'Partial Essay Score')], max_length=20)),
                ('is_solved_now', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentCreatedExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_mcq_questions', models.PositiveIntegerField()),
                ('number_of_essay_questions', models.PositiveIntegerField()),
                ('time_limit', models.PositiveIntegerField(help_text='Time limit in minutes')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('exam_score', models.FloatField(default=0.0)),
                ('result', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('is_solved', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TempExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_questions', models.PositiveIntegerField()),
                ('time_limit', models.PositiveIntegerField(blank=True, help_text='Time limit in minutes', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('result', models.FloatField(blank=True, null=True)),
                ('selected_questions_type', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TempExamAllowedTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_allowedtempexams_per_day', models.PositiveIntegerField(default=3)),
            ],
        ),
    ]
