# Generated by Django 6.0 on 2026-05-09 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('exam', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='essaysubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
        migrations.AddField(
            model_name='exam',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='course.course'),
        ),
        migrations.AddField(
            model_name='exam',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='course.unit'),
        ),
        migrations.AddField(
            model_name='essaysubmission',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='essaysubmissions', to='exam.exam'),
        ),
        migrations.AddField(
            model_name='exammodel',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_models', to='exam.exam'),
        ),
        migrations.AddField(
            model_name='exammodelquestion',
            name='exam_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_questions', to='exam.exammodel'),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_questions', to='exam.exam'),
        ),
        migrations.AddField(
            model_name='question',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coursequestions', to='course.course'),
        ),
        migrations.AddField(
            model_name='question',
            name='similar_questions',
            field=models.ManyToManyField(blank=True, help_text='Questions that are similar to this question', to='exam.question'),
        ),
        migrations.AddField(
            model_name='question',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unitquestions', to='course.unit'),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_questions', to='exam.question'),
        ),
        migrations.AddField(
            model_name='exammodelquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.question'),
        ),
        migrations.AddField(
            model_name='essaysubmission',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exam.question'),
        ),
        migrations.AddField(
            model_name='adminquestionbank',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_question_bank', to='exam.question'),
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categoryquestions', to='exam.questioncategory'),
        ),
        migrations.AddField(
            model_name='randomexambank',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='random_exam_bank', to='exam.exam'),
        ),
        migrations.AddField(
            model_name='randomexambank',
            name='questions',
            field=models.ManyToManyField(related_name='random_exam_bank', to='exam.question'),
        ),
        migrations.AddField(
            model_name='result',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='exam.exam'),
        ),
        migrations.AddField(
            model_name='result',
            name='exam_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam.exammodel'),
        ),
        migrations.AddField(
            model_name='result',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
        migrations.AddField(
            model_name='resulttrial',
            name='exam_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam.exammodel'),
        ),
        migrations.AddField(
            model_name='resulttrial',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trials', to='exam.result'),
        ),
        migrations.AddField(
            model_name='essaysubmission',
            name='result_trial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='essay_submissions', to='exam.resulttrial'),
        ),
        migrations.AddField(
            model_name='studentbank',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_bank', to='exam.question'),
        ),
        migrations.AddField(
            model_name='studentbank',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_bank', to='student.student'),
        ),
        migrations.AddField(
            model_name='studentcreatedexam',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.course'),
        ),
        migrations.AddField(
            model_name='studentcreatedexam',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_exams', to='student.student'),
        ),
        migrations.AddField(
            model_name='studentcreatedexam',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.unit'),
        ),
        migrations.AddField(
            model_name='submission',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='exam.exam'),
        ),
        migrations.AddField(
            model_name='submission',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.question'),
        ),
        migrations.AddField(
            model_name='submission',
            name='result_trial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='exam.resulttrial'),
        ),
        migrations.AddField(
            model_name='submission',
            name='selected_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.answer'),
        ),
        migrations.AddField(
            model_name='submission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
        migrations.AddField(
            model_name='tempexam',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.course'),
        ),
        migrations.AddField(
            model_name='tempexam',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_exams', to='student.student'),
        ),
        migrations.AddField(
            model_name='tempexam',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.unit'),
        ),
        migrations.AddConstraint(
            model_name='tempexamallowedtimes',
            constraint=models.CheckConstraint(condition=models.Q(('id', 1)), name='single_instance_constraint'),
        ),
        migrations.AddIndex(
            model_name='exammodelquestion',
            index=models.Index(fields=['exam_model', 'is_active'], name='exam_exammo_exam_mo_55b195_idx'),
        ),
        migrations.AddIndex(
            model_name='exammodelquestion',
            index=models.Index(fields=['question', 'is_active'], name='exam_exammo_questio_653826_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='exammodelquestion',
            unique_together={('exam_model', 'question')},
        ),
        migrations.AddIndex(
            model_name='adminquestionbank',
            index=models.Index(fields=['created', 'question'], name='exam_adminq_created_4f2b83_idx'),
        ),
        migrations.AddIndex(
            model_name='adminquestionbank',
            index=models.Index(fields=['question', 'created'], name='exam_adminq_questio_6e99fd_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['question_type', 'is_active'], name='exam_questi_questio_b33dde_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['is_active', 'question_type'], name='exam_questi_is_acti_361344_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['id', 'is_active', 'question_type'], name='exam_questi_id_a65d01_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['course', 'is_active', 'question_type'], name='exam_questi_course__9c8829_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['unit', 'is_active', 'question_type'], name='exam_questi_unit_id_10f5b4_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['category', 'is_active', 'question_type'], name='exam_questi_categor_a874b3_idx'),
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['student', 'exam'], name='exam_result_student_2e54ad_idx'),
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['trial', 'added'], name='exam_result_trial_d60aaf_idx'),
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['added', 'student'], name='exam_result_added_51900f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='result',
            unique_together={('student', 'exam')},
        ),
        migrations.AddIndex(
            model_name='resulttrial',
            index=models.Index(fields=['result', 'trial'], name='exam_result_result__18e051_idx'),
        ),
        migrations.AddIndex(
            model_name='resulttrial',
            index=models.Index(fields=['score', 'exam_score'], name='exam_result_score_336a08_idx'),
        ),
        migrations.AddIndex(
            model_name='resulttrial',
            index=models.Index(fields=['student_started_exam_at', 'student_submitted_exam_at'], name='exam_result_student_3627fb_idx'),
        ),
        migrations.AddIndex(
            model_name='resulttrial',
            index=models.Index(fields=['submit_type', 'student_submitted_exam_at'], name='exam_result_submit__0e0e09_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='resulttrial',
            unique_together={('result', 'trial')},
        ),
        migrations.AlterUniqueTogether(
            name='essaysubmission',
            unique_together={('student', 'exam', 'question', 'result_trial')},
        ),
        migrations.AddIndex(
            model_name='studentbank',
            index=models.Index(fields=['student', 'question'], name='exam_studen_student_f03f1c_idx'),
        ),
        migrations.AddIndex(
            model_name='studentbank',
            index=models.Index(fields=['student', 'is_solved_now', 'question'], name='exam_studen_student_3790ee_idx'),
        ),
        migrations.AddIndex(
            model_name='studentbank',
            index=models.Index(fields=['is_solved_now', 'question'], name='exam_studen_is_solv_42225d_idx'),
        ),
        migrations.AddIndex(
            model_name='studentbank',
            index=models.Index(fields=['id', 'student', 'is_solved_now'], name='exam_studen_id_856555_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentbank',
            unique_together={('student', 'question')},
        ),
        migrations.AddIndex(
            model_name='studentcreatedexam',
            index=models.Index(fields=['student', 'created'], name='exam_studen_student_f31d38_idx'),
        ),
        migrations.AddIndex(
            model_name='studentcreatedexam',
            index=models.Index(fields=['course', 'unit'], name='exam_studen_course__237499_idx'),
        ),
        migrations.AddIndex(
            model_name='studentcreatedexam',
            index=models.Index(fields=['created', 'student'], name='exam_studen_created_7d2f6f_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['student', 'exam'], name='exam_submis_student_04f331_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['result_trial', 'is_correct'], name='exam_submis_result__db928e_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['question', 'is_correct'], name='exam_submis_questio_98a3b5_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['student', 'is_correct', 'is_solved'], name='exam_submis_student_c1bfc1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('student', 'exam', 'question', 'result_trial')},
        ),
        migrations.AddIndex(
            model_name='tempexam',
            index=models.Index(fields=['student', 'created'], name='exam_tempex_student_b84730_idx'),
        ),
        migrations.AddIndex(
            model_name='tempexam',
            index=models.Index(fields=['course', 'unit'], name='exam_tempex_course__859b3e_idx'),
        ),
        migrations.AddIndex(
            model_name='tempexam',
            index=models.Index(fields=['created', 'student'], name='exam_tempex_created_1a20ce_idx'),
        ),
    ]
