from django.urls import path

from .views import exam as exam_views
from .views import management as management_views

app_name = "dashboard"

urlpatterns = [
    path("plans/", management_views.PlanListCreateView.as_view(), name="plan-list-create"),
    path("plans/<int:pk>/", management_views.PlanDetailView.as_view(), name="plan-detail"),
    path("discount-coupons/", management_views.DiscountCouponListCreateView.as_view(), name="discount-coupon-list-create"),
    path("discount-coupons/<int:pk>/", management_views.DiscountCouponDetailView.as_view(), name="discount-coupon-detail"),
    path("plans/subscriptions/", management_views.PlanSubscriptionListView.as_view(), name="plan-subscription-list"),
    path("plans/subscriptions/<int:subscription_id>/confirm/", management_views.ConfirmPlanSubscriptionView.as_view(), name="confirm-plan-subscription"),
    path("courses/", management_views.CourseListCreateView.as_view(), name="course-list-create"),
    path("courses/<int:pk>/", management_views.CourseDetailView.as_view(), name="course-detail"),
    path("courses/<int:course_id>/units/", management_views.UnitListCreateView.as_view(), name="unit-list-create"),
    path("units/<int:pk>/", management_views.UnitDetailView.as_view(), name="unit-detail"),
    path("exams/", exam_views.ExamListCreateView.as_view(), name="exam-list-create"),
    path("exam-config/", exam_views.ExamConfigView.as_view(), name="exam-config"),
    path("unsubscribed-exam-config/", exam_views.UnsubscribedExamConfigView.as_view(), name="unsubscribed-exam-config"),
    path("exams/<int:pk>/", exam_views.ExamDetailView.as_view(), name="exam-detail"),
    path("question-categories/", exam_views.QuestionCategoryListCreateView.as_view(), name="question-category-list-create"),
    path("question-categories/<int:pk>/", exam_views.QuestionCategoryRetrieveUpdateDestroyView.as_view(), name="question-category-detail"),
    path("years/", exam_views.YearListCreateView.as_view(), name="year-list-create"),
    path("years/all/", exam_views.YearListAllView.as_view(), name="year-list-all"),
    path("years/<int:pk>/", exam_views.YearRetrieveUpdateDestroyView.as_view(), name="year-detail"),
    path("questions/", exam_views.QuestionListCreateView.as_view(), name="question-list-create"),
    path("questions/<int:pk>/", exam_views.QuestionRetrieveUpdateDestroyView.as_view(), name="question-detail"),
    path("questions/bulk-create/", exam_views.BulkQuestionCreateView.as_view(), name="bulk-question-create"),
    path("questions/bulk/", exam_views.BulkQuestionCreateView.as_view(), name="bulk-question-create-alias"),
    path("questions/count/", exam_views.QuestionCountView.as_view(), name="question-count"),
    path("answers/", exam_views.AnswerListCreateView.as_view(), name="answer-list-create"),
    path("answers/<int:pk>/", exam_views.AnswerRetrieveUpdateDestroyView.as_view(), name="answer-detail"),
    path("exams/<int:exam_id>/questions/", exam_views.ExamQuestionListCreateView.as_view(), name="exam-question-list-create"),
    path("results/top-students/", exam_views.TopStudentResultsView.as_view(), name="top-student-results"),
    path("results/", exam_views.ResultListView.as_view(), name="result-list"),
    path("results/<int:result_id>/reduce-trial/", exam_views.ReduceResultTrialView.as_view(), name="reduce-result-trial"),
    path("results/<int:result_id>/detail/", exam_views.ExamResultDetailView.as_view(), name="exam-result-detail"),
    path("results/<int:result_id>/trials/", exam_views.ResultTrialsView.as_view(), name="result-trials"),
    path("results/<int:result_id>/trials/<int:result_trial_id>/detail/", exam_views.ExamResultDetailForTrialView.as_view(), name="exam-result-trial-detail"),
    path("trials/", exam_views.AllTrialsListView.as_view(), name="all-trials-list"),
    path("result-trials/", exam_views.ResultTrialListCreateView.as_view(), name="result-trial-list-create"),
    path("result-trials/<int:pk>/", exam_views.ResultTrialRetrieveUpdateDestroyView.as_view(), name="result-trial-detail"),
    path("result-trials/<int:trial_id>/detail/", exam_views.ResultTrialDetailView.as_view(), name="result-trial-expanded-detail"),
    path("exams/<int:exam_id>/students/took/", exam_views.StudentsTookExamAPIView.as_view(), name="students-took-exam"),
    path("exams/<int:exam_id>/students/not-took/", exam_views.StudentsDidNotTakeExamAPIView.as_view(), name="students-not-took-exam"),
    path("students/<int:student_id>/exams/taken/", exam_views.ExamsTakenByStudentAPIView.as_view(), name="student-exams-taken"),
    path("students/<int:student_id>/exams/not-taken/", exam_views.ExamsNotTakenByStudentAPIView.as_view(), name="student-exams-not-taken"),
    path("students/unsubscribed-exam-limits/", exam_views.StudentUnsubscribedExamLimitListView.as_view(), name="student-unsubscribed-exam-limit-list"),
    path("students/<int:student_id>/unsubscribed-exam-limit/", exam_views.StudentUnsubscribedExamLimitView.as_view(), name="student-unsubscribed-exam-limit"),
    path("exams/<int:exam_id>/trials/delete-first/", exam_views.DeleteFirstResultTrialForExamView.as_view(), name="delete-first-result-trial-for-exam"),
]
