# Generated by Django 6.0 on 2026-05-09 09:48

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(max_length=100)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_created_at', models.DateTimeField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('user_type', models.CharField(choices=[('student', 'Student'), ('admin', 'Admin')], max_length=20)),
                ('parent_phone', models.CharField(blank=True, help_text='Only applicable for students', max_length=20, null=True)),
                ('government', models.CharField(blank=True, choices=[('1', 'Cairo'), ('2', 'Alexandria'), ('3', 'Kafr El Sheikh'), ('4', 'Dakahleya'), ('5', 'Sharkeya'), ('6', 'Gharbeya'), ('7', 'Monefeya'), ('8', 'Qalyubia'), ('9', 'Giza'), ('10', 'Bani-Sweif'), ('11', 'Fayoum'), ('12', 'Menya'), ('13', 'Assiut'), ('14', 'Sohag'), ('15', 'Qena'), ('16', 'Luxor'), ('17', 'Aswan'), ('18', 'Red Sea'), ('19', 'Behera'), ('20', 'Ismailia'), ('21', 'Suez'), ('22', 'Port-Said'), ('23', 'Damietta'), ('24', 'Marsa Matrouh'), ('25', 'Al-Wadi Al-Gadid'), ('26', 'North Sinai'), ('27', 'South Sinai')], max_length=2, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('max_allowed_devices', models.PositiveIntegerField(default=2, help_text='Maximum number of devices allowed for this student (admin can adjust per student)')),
                ('is_banned', models.BooleanField(default=False, help_text='Whether this user is banned from logging in')),
                ('banned_at', models.DateTimeField(blank=True, help_text='When this user was banned', null=True)),
                ('ban_reason', models.TextField(blank=True, help_text='Reason for banning this user', null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SecurityBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, help_text='Phone number that is blocked', max_length=20)),
                ('block_type', models.CharField(choices=[('login', 'Failed Login Attempts'), ('password_reset', 'Password Reset Request'), ('combined', 'Combined (Login + Reset)')], default='login', help_text='Type of operation that was blocked', max_length=20)),
                ('blocked_at', models.DateTimeField(auto_now_add=True, help_text='When the block was initiated')),
                ('blocked_until', models.DateTimeField(help_text='When the block expires')),
                ('block_level', models.PositiveIntegerField(default=1, help_text='Progressive block level (1, 2, 3, etc.)')),
                ('consecutive_blocks', models.PositiveIntegerField(default=1, help_text='Number of consecutive blocks for this phone number')),
                ('is_active', models.BooleanField(default=True, help_text='Whether block is currently active')),
                ('manually_unblocked', models.BooleanField(default=False, help_text='Whether block was manually lifted by admin')),
                ('unblocked_at', models.DateTimeField(blank=True, help_text='When block was manually removed', null=True)),
                ('unblock_reason', models.TextField(blank=True, help_text='Reason for manual unblock', null=True)),
                ('failed_attempts', models.JSONField(default=list, help_text='List of failed attempt details (timestamps, IPs, device_ids, etc.)')),
                ('ip_addresses', models.JSONField(default=list, help_text='IP addresses involved in failed attempts')),
                ('user_agents', models.JSONField(default=list, help_text='User agents involved in failed attempts')),
                ('device_ids', models.JSONField(default=list, help_text='Device IDs involved in failed attempts')),
                ('unblocked_by', models.ForeignKey(blank=True, help_text='Admin who manually unblocked', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unblocked_security_blocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Security Block',
                'verbose_name_plural': 'Security Blocks',
                'ordering': ['-blocked_at'],
            },
        ),
        migrations.CreateModel(
            name='AuthenticationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, help_text='Phone number attempting authentication', max_length=20)),
                ('attempt_type', models.CharField(choices=[('login', 'Login Attempt'), ('password_reset', 'Password Reset Request')], help_text='Type of authentication attempt', max_length=20)),
                ('result', models.CharField(choices=[('success', 'Successful'), ('failed', 'Failed'), ('blocked', 'Blocked')], help_text='Result of the attempt', max_length=20)),
                ('attempted_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the attempt was made')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the attempt', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string', null=True)),
                ('device_id', models.CharField(blank=True, db_index=True, help_text='Device ID from the mobile app', max_length=255, null=True)),
                ('failure_reason', models.TextField(blank=True, help_text='Reason for failure (e.g., wrong password)', null=True)),
                ('related_block', models.ForeignKey(blank=True, help_text='Security block that prevented this attempt', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to='accounts.securityblock')),
            ],
            options={
                'verbose_name': 'Authentication Attempt',
                'verbose_name_plural': 'Authentication Attempts',
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_token', models.CharField(help_text='Unique token identifying this device session', max_length=64, unique=True)),
                ('device_id', models.CharField(blank=True, help_text='Unique device identifier from mobile app (Android ID / iOS identifierForVendor)', max_length=255, null=True)),
                ('device_name', models.CharField(blank=True, help_text="Auto-detected device type (e.g., 'iPhone', 'Android Device', 'Windows PC')", max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the device (used as fallback if device_id not provided)', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser/App User-Agent string', null=True)),
                ('device_info', models.JSONField(blank=True, help_text='Additional device information (legacy field, kept for compatibility)', null=True)),
                ('logged_in_at', models.DateTimeField(auto_now_add=True, help_text='When this device was first logged in')),
                ('last_used_at', models.DateTimeField(auto_now=True, help_text='Last time this device made an API request')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this device is currently active (can be disabled by admin)')),
                ('is_banned', models.BooleanField(default=False, help_text='Whether this device is banned from logging in')),
                ('banned_at', models.DateTimeField(blank=True, help_text='When this device was banned', null=True)),
                ('ban_reason', models.TextField(blank=True, help_text='Reason for banning this device', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Device',
                'verbose_name_plural': 'User Devices',
                'ordering': ['-last_used_at'],
            },
        ),
        migrations.CreateModel(
            name='DeletedUserArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_user_id', models.IntegerField(help_text='Original user ID before deletion')),
                ('username', models.CharField(help_text='Phone number used as username', max_length=150)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('user_type', models.CharField(choices=[('student', 'Student'), ('admin', 'Admin')], max_length=20)),
                ('parent_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('government', models.CharField(blank=True, choices=[('1', 'Cairo'), ('2', 'Alexandria'), ('3', 'Kafr El Sheikh'), ('4', 'Dakahleya'), ('5', 'Sharkeya'), ('6', 'Gharbeya'), ('7', 'Monefeya'), ('8', 'Qalyubia'), ('9', 'Giza'), ('10', 'Bani-Sweif'), ('11', 'Fayoum'), ('12', 'Menya'), ('13', 'Assiut'), ('14', 'Sohag'), ('15', 'Qena'), ('16', 'Luxor'), ('17', 'Aswan'), ('18', 'Red Sea'), ('19', 'Behera'), ('20', 'Ismailia'), ('21', 'Suez'), ('22', 'Port-Said'), ('23', 'Damietta'), ('24', 'Marsa Matrouh'), ('25', 'Al-Wadi Al-Gadid'), ('26', 'North Sinai'), ('27', 'South Sinai')], max_length=2, null=True)),
                ('max_allowed_devices', models.PositiveIntegerField(default=2)),
                ('was_banned', models.BooleanField(default=False)),
                ('ban_reason', models.TextField(blank=True, null=True)),
                ('original_created_at', models.DateTimeField(blank=True, help_text='When the user account was originally created', null=True)),
                ('deleted_at', models.DateTimeField(auto_now_add=True, help_text='When the user was deleted')),
                ('is_restored', models.BooleanField(default=False, help_text='Whether this deleted user has been restored')),
                ('deletion_reason', models.TextField(blank=True, help_text='Reason for deletion', null=True)),
                ('user_data_snapshot', models.JSONField(default=dict, help_text='Complete snapshot of user data at deletion time')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='Admin who deleted this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Deleted User Archive',
                'verbose_name_plural': 'Deleted Users Archive',
                'ordering': ['-deleted_at'],
                'indexes': [models.Index(fields=['username'], name='accounts_de_usernam_42ae9f_idx'), models.Index(fields=['original_user_id'], name='accounts_de_origina_088d79_idx'), models.Index(fields=['-deleted_at'], name='accounts_de_deleted_70d8b5_idx')],
            },
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Phone number to send OTP to', max_length=20)),
                ('otp_code', models.CharField(help_text='6-digit OTP code', max_length=6)),
                ('purpose', models.CharField(choices=[('signup', 'Signup Verification'), ('password_reset', 'Password Reset'), ('phone_verification', 'Phone Verification'), ('other', 'Other')], default='signup', help_text='Purpose of this OTP', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When OTP was generated')),
                ('expires_at', models.DateTimeField(help_text='When OTP expires')),
                ('is_verified', models.BooleanField(default=False, help_text='Whether OTP was successfully verified')),
                ('verified_at', models.DateTimeField(blank=True, help_text='When OTP was verified', null=True)),
                ('is_used', models.BooleanField(default=False, help_text='Whether OTP has been used (prevents reuse)')),
                ('verification_attempts', models.PositiveIntegerField(default=0, help_text='Number of failed verification attempts')),
                ('user', models.ForeignKey(blank=True, help_text='Associated user (if any)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OTP',
                'verbose_name_plural': 'OTPs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_number', 'purpose', '-created_at'], name='accounts_ot_phone_n_b558e1_idx'), models.Index(fields=['phone_number', 'is_used', 'is_verified'], name='accounts_ot_phone_n_49e18a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='securityblock',
            index=models.Index(fields=['phone_number', 'is_active'], name='accounts_se_phone_n_dccd60_idx'),
        ),
        migrations.AddIndex(
            model_name='securityblock',
            index=models.Index(fields=['phone_number', 'block_type', 'is_active'], name='accounts_se_phone_n_efe08f_idx'),
        ),
        migrations.AddIndex(
            model_name='securityblock',
            index=models.Index(fields=['-blocked_at'], name='accounts_se_blocked_68269d_idx'),
        ),
        migrations.AddIndex(
            model_name='securityblock',
            index=models.Index(fields=['blocked_until'], name='accounts_se_blocked_dd8f56_idx'),
        ),
        migrations.AddIndex(
            model_name='authenticationattempt',
            index=models.Index(fields=['phone_number', '-attempted_at'], name='accounts_au_phone_n_8e4eb7_idx'),
        ),
        migrations.AddIndex(
            model_name='authenticationattempt',
            index=models.Index(fields=['phone_number', 'attempt_type', 'result', '-attempted_at'], name='accounts_au_phone_n_442c11_idx'),
        ),
        migrations.AddIndex(
            model_name='authenticationattempt',
            index=models.Index(fields=['-attempted_at'], name='accounts_au_attempt_176650_idx'),
        ),
        migrations.AddIndex(
            model_name='userdevice',
            index=models.Index(fields=['user', 'device_id', 'is_active'], name='accounts_us_user_id_82d166_idx'),
        ),
        migrations.AddIndex(
            model_name='userdevice',
            index=models.Index(fields=['user', 'ip_address', 'is_active'], name='accounts_us_user_id_4c1fc9_idx'),
        ),
    ]
