# Generated by Django 6.0 on 2026-07-26 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deleteduserarchive',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('not_defined', 'Not Defined')], default='not_defined', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('not_defined', 'Not Defined')], default='not_defined', max_length=20),
        ),
    ]
